# =================================================================== #
#                           GENERAL SETTINGS                          #
# =================================================================== #

# Enable this to see detailed diagnostic messages in the console.
# This is useful for debugging issues with hooks or bucket usage.
debug-mode: false

# Enable automatic update checking and notifications for admins
update-checker:
  enabled: true
  notify-admins: true
  check-interval: 24  # hours

# Message settings
messages:
  # When true, only update notifications will be shown (all other messages from messages.yml will be disabled)
  only-update-messages: false

# Performance and safety settings
performance:
  # Maximum number of blocks that can be affected by drain-area buckets per use
  max-drain-blocks: 1000
  # Global cooldown between bucket uses (in ticks, 20 ticks = 1 second)
  global-cooldown: 5
  # Enable async processing for large drain operations
  async-processing: true

# Integration settings for protection plugins
integrations:
  # Automatically detect and hook into protection plugins
  auto-detect-hooks: true
  # List of protection plugins to explicitly enable/disable
  hooks:
    worldguard: true
    griefprevention: true
    towny: true
    lands: true
    plotsquared: true
    residence: true
    superiorskyblock: true

# World restrictions
world-settings:
  # Worlds where infinite buckets are completely disabled
  disabled-worlds: []
  # Default nether restrictions (can be overridden per bucket)
  default-nether-restriction: false
  # Worlds with special rules
  world-rules:
    # Example:
    # nether:
    #   allow-water-buckets: false
    #   allow-lava-buckets: true

# =================================================================== #
#                          BUCKET DEFINITIONS                         #
# =================================================================== #
#
# Bucket definitions have been moved to buckets.yml for better organization
# and more advanced configuration options. Please refer to buckets.yml to
# configure all bucket types and behaviors.
#