debug-mode: false

buckets:
  water:
    material: "WATER_BUCKET"
    display-name: "<aqua>Infinite Water Bucket</aqua>"
    lore:
      - "<gray>A bucket filled with an endless supply of water.</gray>"
    permission: "infb.use.water"
    works-in-nether: false

  lava:
    material: "LAVA_BUCKET"
    display-name: "<gold>Infinite Lava Bucket</gold>"
    lore:
      - "<gray>A bucket filled with an endless supply of lava.</gray>"
    permission: "infb.use.lava"

    works-in-nether: true
