name: InfiniteBuckets
version: ${project.version}
main: me.djtmk.InfiniteBuckets.Main
api-version: 1.21
folia-supported: true
authors: [ djtmk ]
description: Infinite Water and Lava Buckets
website: https://builtbybit.com/resources/infinitebuckets.61863/
softdepend: [SuperiorSkyblock2]

commands:
  infb:
    description: Main command for Infinite Buckets
    usage: /<command> [reload|give|debug]
    aliases: [ infinitebuckets, ib ]
permissions:
  infb.use.water:
    description: Allows use of infinite water buckets
    default: true
  infb.use.lava:
    description: Allows use of infinite lava buckets
    default: true
  infb.admin:
    description: Allows reload, give, and debug commands
    default: op
