name: InfiniteBuckets
version: 1.2
main: me.djtmk.InfiniteBuckets.Main
api-version: 1.21
authors: [ djtmk ]
description: Infinite Water and Lava Buckets
commands:
  infb:
    description: Main command for Infinite Buckets
    usage: /<command> [reload|give]
    aliases: [ infinitebuckets, ib ]
permissions:
  infb.use.water:
    description: Allows use of infinite water buckets
    default: true
  infb.use.lava:
    description: Allows use of infinite lava buckets
    default: true
  infb.admin:
    description: Allows reload and give commands
    default: op