name: InfiniteBuckets
version: ${project.version}
main: me.djtmk.InfiniteBuckets.Main
api-version: '1.21'
folia-supported: true
authors: [ djtmk ]
description: Provides customizable infinite water and lava buckets.
website: https://modrinth.com/plugin/infinitebuckets

softdepend:
  - SuperiorSkyblock2
  - WorldGuard
  - GriefPrevention
  - Towny
  - Lands
  - PlotSquared
  - Residence

commands:
  infinitebuckets:
    description: Main command for InfiniteBuckets.
    aliases: [infb, ib]

permissions:
  infb.admin:
    description: Allows access to all admin commands for InfiniteBuckets.
    default: op
  infb.use.water:
    description: Allows use of the infinite water bucket.
    default: true
  infb.use.lava:
    description: Allows use of the infinite lava bucket.
    default: true