name: InfiniteBuckets
version: 1.3
main: me.djtmk.InfiniteBuckets.Main
api-version: 1.21
authors: [ djtmk ]
description: Infinite Water and Lava Buckets
softdepend: [SuperiorSkyblock2]
commands:
  infb:
    description: Main command for Infinite Buckets
    usage: /<command> [reload|give|debug]
    aliases: [ infinitebuckets, ib ]
permissions:
  infb.use.water:
    description: Allows use of infinite water buckets
    default: true
  infb.use.lava:
    description: Allows use of infinite lava buckets
    default: true
  infb.admin:
    description: Allows reload, give, and debug commands
    default: op